### ISSUE TITLE
JSX double quotes?

### ISSUE THREAD

**Issue by madbence** [purposeindustries/eslint-config-pi#1]
what's the reason behind this?

**Comment by ruffle1986** [comment]
@madbence The reason behind this is the choice I made. I write html attributes in this way and it shows to the developer that it's not a js string expression but a jsx attribue value. I also wanted this to be consistent. But to be honest, I rarely use it.

**Comment by madbence** [comment]
but it's exactly that, just a string literal :wink:

**Comment by ruffle1986** [comment]
and we can write it with double quotes. ;)
