### ISSUE TITLE
add security eslint config

### ISSUE THREAD

**Issue by ruffle1986** [purposeindustries/eslint-config-pi#3]
Shall we use this config by default?

https://github.com/nodesecurity/eslint-plugin-security

**Comment by oroce** [comment]
sure we can add

**Comment by madbence** [comment]
`detect-unsafe-regex` looks nice! the other ones are not so useful :frog:

**Comment by ruffle1986** [comment]
I think this rule set will be extended in the future with further useful rules so it's a nice-to-have

**Comment by ruffle1986** [comment]
closing this issue due to lack of interest
